services:
    app:
        build:
            args:
                user: growmodo
                uid: 1000
            context: .docker
            dockerfile: Dockerfile
        ports:
            - 6001:6001
        image: growmodo_hub_api:1.0.0
        container_name: growmodo_hub_api-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
            - ./.docker/php/local.ini:/usr/local/etc/php/local.ini/:rw
            - growmodo_hub_api-cert:/certs/:rw

    postgres:
        image: postgres:latest
        container_name: growmodo_hub_api-postgres
        restart: always
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_HOST: ${DB_HOST}
            POSTGRES_PORT: 5432
        ports:
            - 5432:5432
        volumes:
            - ./.docker/postgres:/docker-entrypoint-initdb.d/:rw
            - growmodo_hub_api-postgres_data:/var/lib/postgresql/data/:rw

    nginx:
        image: nginx:alpine
        container_name: growmodo_hub_api-nginx
        restart: always
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./:/var/www
            - ./.docker/nginx:/etc/nginx/conf.d/:ro
            - growmodo_hub_api-cert:/etc/nginx/certs/:ro

    pgadmin:
        image: dpage/pgadmin4:latest
        container_name: growmodo_hub_api-pgadmin4
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: ${MAIL_FROM_ADDRESS}
            PGADMIN_DEFAULT_PASSWORD: ${MAIL_PASSWORD}
        ports:
            - 5050:80
        volumes:
            - growmodo_hub_api-pgadmin:/var/lib/pgadmin/:rw

volumes:
    growmodo_hub_api-cert:
    growmodo_hub_api-pgadmin:
    growmodo_hub_api-postgres_data:
